tap 'git-duet/tap'
tap 'neovim/neovim'

brew 'chruby'
brew 'ctags'
brew 'direnv'
brew 'git-duet'
brew 'neovim/neovim/neovim'
brew 'nvm'
brew 'readline'
brew 'ruby-build'
brew 'the_silver_searcher'

cask 'firefox'
cask 'google-chrome'
cask 'rowanj-gitx'
cask 'slack'
