-- source ~/.vimrc
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.ack"
require "user.cmp"
require "user.colorscheme"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.related-files"
require "user.autopairs"
require "user.gitsigns"
require "user.indent-blankline"
require "user.nvim-test"
require "user.sidebar"
require "user.colorizer"
